version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development  # Set this as per your environment
    volumes:
      - .:/app
    # Optional: Define additional service settings like restart policy
    # restart: always
